kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  storageClassName: ${STORAGE_CLASS}
  volumeMode: Filesystem
