kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#  storageClassName: ${STORAGE_CLASS}
  volumeMode: Filesystem
