apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus100-dev
  namespace: dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: dev
    repoURL: https://github.com/mmartofel/quarkus100-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
