apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: test
    repoURL: 'https://github.com/mmartofel/quarkus100-deployment.git'
    targetRevision: HEAD
  project: default

